name: Deploy live update

on:
  push:
    branches:
      - 'main'

jobs:
  LiveUpdate-Deploy:
    runs-on: ubuntu-latest

    env:
      IONIC_TOKEN: ${{ secrets.IONIC_TOKEN }}
      APP_ID: '42f81456'
    
    steps:
    - name: install cloud cli
      run: curl -sL https://ionic.io/get-ionic-cloud-cli | bash
    
    - name: checkout repository
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: install dependencies
      run: npm install

    - name: build project
      run: npm run build

    - name: bundle artifact
      run: ionic-cloud live-update bundle-artifact --build-dir=dist --signing-key="${{ secrets.IONIC_PRIVATE_KEY }}" --output-path=build.zip
      
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
        
    - name: copy bundle to aws
      run: |
        aws s3 cp build.zip s3://shlu-github-actions-s3-demo

    - name: register artifact
      run: |
        ionic-cloud live-update register-artifact \
        --app-id=$APP_ID \
        --commit-ref=$GITHUB_SHA \
        --commit-ref=$GITHUB_REF \
        --commit-message=${{ github.event.head_commit.message }} \
        --artifact-url=https://shlu-github-actions-s3-demo.s3.us-east-2.amazonaws.com/build.zip
